# Generated by Django 5.2.8 on 2025-12-07 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_users', models.JSONField(default=list)),
                ('weekly_top_users', models.JSONField(default=list)),
                ('classroom_top_users', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members_count', models.IntegerField(default=0)),
                ('total_challenges', models.IntegerField(default=0)),
                ('solved_challenges_count', models.IntegerField(default=0)),
                ('average_completion', models.FloatField(default=0.0)),
                ('average_challenge_time', models.FloatField(default=0.0)),
                ('fastest_challenge_time', models.FloatField(default=0.0)),
                ('comments_count', models.IntegerField(default=0)),
                ('total_submissions', models.IntegerField(default=0)),
                ('last_activity_date', models.DateTimeField(blank=True, null=True)),
                ('top_performers', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='my_app.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='MentorDashboardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_classrooms_count', models.IntegerField(default=0)),
                ('active_classrooms_count', models.IntegerField(default=0)),
                ('total_students', models.IntegerField(default=0)),
                ('total_challenges', models.IntegerField(default=0)),
                ('total_submissions', models.IntegerField(default=0)),
                ('average_submission_per_student', models.FloatField(default=0.0)),
                ('last_activity_date', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenges_solved', models.IntegerField(default=0)),
                ('total_points', models.IntegerField(default=0)),
                ('classrooms_joined', models.IntegerField(default=0)),
                ('global_rank', models.IntegerField(default=0)),
                ('challenges_not_started', models.IntegerField(default=0)),
                ('challenges_in_progress', models.IntegerField(default=0)),
                ('submissions_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('average_solve_time', models.FloatField(default=0.0)),
                ('fastest_solve_time', models.FloatField(default=0.0)),
                ('last_submission_date', models.DateTimeField(blank=True, null=True)),
                ('last_activity_date', models.DateTimeField(blank=True, null=True)),
                ('weekly_points', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
