# Generated by Django 5.2.8 on 2025-12-08 19:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='points',
            field=models.IntegerField(default=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
