# Generated by Django 5.2.8 on 2025-12-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_leaderboardcache_classroomstats_mentordashboardstats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='not_started_count',
            field=models.IntegerField(default=0),
        ),
    ]
