# Generated by Django 5.2.8 on 2025-12-08 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_challenge_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='points',
        ),
    ]
