# Generated by Django 5.2.8 on 2025-12-06 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_rename_requirement_value_badge_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='challenge',
            name='constraints',
            field=models.TextField(blank=True, help_text='Write each constraint on a separate line.'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='example_explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='hidden_tests',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='starter_code',
            field=models.TextField(blank=True),
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='tags',
        ),
        migrations.AddField(
            model_name='challenge',
            name='tags',
            field=models.ManyToManyField(blank=True, to='my_app.tag'),
        ),
    ]
