# Generated by Django 5.2.8 on 2025-12-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_userstats_not_started_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
