# Generated by Django 5.2.8 on 2025-12-07 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_profile'),
        ('my_app', '0003_tag_challenge_constraints_and_more'),
    ]

    operations = [
    ]
