# Generated by Django 5.2.8 on 2025-12-08 20:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_remove_challenge_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='points',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
