# Generated by Django 5.2.8 on 2025-12-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_merge_20251207_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='constraints',
            field=models.TextField(blank=True),
        ),
    ]
