# Generated by Django 5.2.8 on 2025-12-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_alter_challenge_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('java', 'Java'), ('cpp', 'C++'), ('c', 'C'), ('ruby', 'Ruby'), ('go', 'Go'), ('php', 'PHP'), ('swift', 'Swift'), ('kotlin', 'Kotlin')], default='python', max_length=20),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
