# Generated by Django 5.0.6 on 2025-12-08 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_alter_classroom_slug_alter_submission_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='points',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='points',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='badge',
            name='requirement_type',
            field=models.CharField(choices=[('first_solve', 'First Solve'), ('challenge_count', 'Challenge Count'), ('classroom_complete', 'Classroom Complete')], max_length=30),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='hidden_tests',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='submission',
            name='points_awarded',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
