# Generated by Django 5.2.8 on 2025-12-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_challenge_points_profile_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.CharField(default='Beginner', max_length=20),
        ),
    ]
