# Generated by Django 5.0.6 on 2025-12-10 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_comment_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='text',
        ),
    ]
