# Generated by Django 5.2.8 on 2025-12-10 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_comment_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
    ]
