# Generated by Django 5.2.8 on 2025-12-10 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_alter_comment_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='text',
        ),
    ]
