# Generated by Django 5.2.8 on 2025-12-10 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_rename_content_comment_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
