# Generated by Django 5.0.6 on 2025-12-10 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_alter_comment_options_rename_content_comment_text'),
        ('my_app', '0012_alter_comment_options_rename_text_comment_content_and_more'),
    ]

    operations = [
    ]
