# Generated by Django 5.0.6 on 2025-12-10 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_merge_20251210_1939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='content',
        ),
    ]
