# Generated by Django 5.2.8 on 2025-12-10 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_challengeprogress'),
        ('my_app', '0014_alter_comment_options_rename_text_comment_content'),
    ]

    operations = [
    ]
