# Generated by Django 5.2.8 on 2025-12-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_merge_20251210_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
