# Generated by Django 5.2.8 on 2025-12-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0016_submission_attempt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
