# Generated by Django 5.0.6 on 2025-12-11 11:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0018_alter_submission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='solved_challenges',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
