# Generated by Django 5.0.6 on 2025-12-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0020_category_challenge_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('error', 'Error'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
