# Generated by Django 5.0.6 on 2025-12-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0021_alter_submission_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='category',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='solved_challenges',
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('error', 'Error')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
